### PR TITLE
neat project! - made some server improvements and PEP-8 formatting

### PR DESCRIPTION
**Pull request by suresttexas00**
-Made server return a proper html page (was sending text because it was sending the entire `res` object)
-made if-elif-else statements only work with path data and status codes (so that re-directs work properly).
-PEP 8 formatting (spaces versus tabs primarily).
-added favicon capability (browsers send GET requests for favicon; thought I would oblige them).
-added background clouds file.
-added proper try:except shutdown to prevent ports remaining bound.
-add more valid paths and redirects.

Really cool, helpful project!  Good for getting into the basics of making a web server in Python! Thanks!

### CODE REVIEW

**Comment by davidharting** [comment]
By the way @suresttexas00, after playing around a little, it looks I wrote this using WebOb version 1.3.1. The newer APIs don't allbw for some of what I do in `server.py`. It also looks like the standard lib `socket` API has changed a bit since I wrote this in 2015, so I cannot get it to run. If you were able to get it to run, let me know what you had to do!

I also cannot remember if I wrote this targeting python 2 or python 3! I should have put it in the readme :/

**Comment by suresttexas00** [comment]
If you could tell me what errors you get, I'll see what I can do.  I run both versions and most projects I attempt to keep compatible with both (and at least 2.7).  It ran ok for me.

**Comment by suresttexas00** [comment]
I rechecked this out now that I had time to play with it again.  It looks like it was a Py2 project since webob seems missing from the python 3 standard modules (on my system anyway).  I found a syntax problem with my exception clause under py3.  As far as sockets, I believe your use of sockets is still correct.  This is still completely valid usage (I use the same code with different ports on other projects):
```
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.bind(('', 8080))
    sock.listen(5)
...
    conn, client_address = sock.accept()
    request = conn.recv(1024)
```

I should be pretty easy to re-invent this wheel and parse our GET data to find the `location` and `status_code`, which is all we are really using webob here for; the response we send is just raw data (html, text, pictures, whatever...)

Oh, yes, and I am submitting a change to the disk reading to use `with open` (which Python will automatically close the file object for us once it is read)

**Comment by suresttexas00** [comment]
Glad to share the feedback and thanks for posting it.  It was very helpful.

**Pull request merged**
